# Generated by Django 2.2.5 on 2019-10-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
    ]
