# Generated by Django 2.2.5 on 2019-10-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResterModelOfCustomer',
            fields=[
                ('restermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resterApp.ResterModel')),
                ('coupon', models.CharField(max_length=20)),
            ],
            bases=('resterApp.restermodel',),
        ),
    ]
