# Generated by Django 2.2.5 on 2019-10-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resterApp', '0003_auto_20191016_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponerModel',
            new_name='CouponerClientModel',
        ),
    ]
